#!/bin/bash

param=all
if [ $# -eq 0 ]; then param="none"; fi
file=LowerBound

# compile libraries
if [ $param == "all" ]; then
 gfortran -c FMSAVE.f90
 gfortran -c FMZM90.f90
 gfortran -c FM.f90 
fi

# link 
gfortran -o ~/bin/LowerBound -w $file.f90 lanczos.f90 bounds_MP.f90 FM.o FMSAVE.o FMZM90.o  -llapack
